
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5