/**
 * An interface representing a generator that can produce values of type T. It defines a `generate` method that can be called with any number of arguments of unknown types and returns either a value of type T or a Promise that resolves to a value of type T.
 * @template T - The type of the values generated by the generator.
 */
export interface Generator<T> {
    generate(...args: unknown[]): T | Promise<T>;
}
