import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    api: [
        {
            type: 'doc',
            id: 'index',
            label: 'AxiSpark.js',
        },
        {
            type: 'category',
            label: 'Packages',
            items: [
                {
                    dirName: '@axisparkjs',
                    type: 'autogenerated'
                }
            ],
        },
    ],
};

export default sidebars;