name: CD - PRE

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish PRE packages
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/heads/release/')

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: "@axisparkjs"

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run ci:build

      - name: Enter prerelease mode
        if: hashFiles('.changeset/pre.json') == ''
        run: npx changeset pre enter pre

      - name: Version prerelease
        run: npx changeset version

      - name: Build packages with prerelease versions
        run: npm run ci:build

      - name: Generate other package files
        run: |
            find packages -mindepth 2 -maxdepth 2 -type f -name package.json -exec sh -c 'cp README.md "$(dirname "$1")/README.md"' _ {} \;
            find packages -mindepth 2 -maxdepth 2 -type f -name package.json -exec sh -c 'cp LICENSE "$(dirname "$1")/LICENSE"' _ {} \;

      - name: Publish packages
        run: npm run cd:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit prerelease state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .changeset package.json package-lock.json packages/*/package.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          VERSION=$(node -p "require('./package.json').version")

          git commit -m "chore: release ${VERSION}"
          git push