name: Packages CD

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    # Seguridad extra: solo permite publicar desde main
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run ci:build

      - name: Publish packages
        run: npm run cd:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}